// ===== Car Data - 19 Models =====
const cars = [
    {
        id: 1,
        name: "BYD Atto 2 301KM",
        nameCn: "元UP智驾版 301KM领航型",
        nameVn: "BYD Atto 2 301KM",
        type: "BEV",
        body: "suv",
        range: "301km",
        power: "70kW",
        battery: "Blade Battery 32kWh",
        fob: 8.94,
        market: 13.35,
        tag: "hot",
        desc: "SUV điện phổ thông, giá rẻ nhất phân khúc",
        descLong: "BYD Atto 2 (元UP) là mẫu SUV điện nhỏ gọn, được thiết kế dành riêng cho thị trường thành thị. Với giá FOB chỉ 8.94万 nhân dân tệ, đây là mẫu xe điện hợp lý nhất trên thị trường Việt Nam, rẻ hơn 30% so với đại lý chính hãng. Xe đã có chứng nhận VTA, thông quan dễ dàng.",
        img: "https://aka.doubaocdn.com/s/FyzbEEuhpc",
        gallery: [
            "https://aka.doubaocdn.com/s/FyzbEEuhpc",
            "https://aka.doubaocdn.com/s/qSUsLsT2c8",
            "https://aka.doubaocdn.com/s/vumoQMpfhT"
        ],
        specs: {
            "Kích thước": "4310×1830×1675mm",
            "Chiều dài cơ sở": "2620mm",
            "Quãng đường CLTC": "301km",
            "Công suất động cơ": "70kW (95 mã lực)",
            "Mô-men xoắn": "180Nm",
            "Dung lượng pin": "32kWh",
            "Loại pin": "Blade Battery (LFP)",
            "Sạc nhanh DC": "30%-80% trong 30 phút",
            "Sạc chậm AC": "6.6kW",
            "Tốc độ tối đa": "150km/h",
            "0-100km/h": "~10 giây",
            "Số chỗ ngồi": "5 chỗ"
        },
        features: [
            "Màn hình trung tâm 12.8 inch",
            "Đèn LED toàn xe",
            "Camera 360 độ",
            "Cảnh báo điểm mù",
            "Giữ làn đường",
            "Phanh khẩn cấp tự động",
            "Điều hòa tự động",
            "Lốp 16 inch",
            "Khe cắm sạc Type 2",
            "Khởi động không chìa khóa"
        ],
        competitor: { name: "VinFast VF 5", price: 14.2, range: "300km" }
    },
    {
        id: 2,
        name: "BYD Atto 2 401KM",
        nameCn: "元UP智驾版 401KM活力型",
        nameVn: "BYD Atto 2 401KM",
        type: "BEV",
        body: "suv",
        range: "401km",
        power: "70kW",
        battery: "Blade Battery 45kWh",
        fob: 11.08,
        market: 16.38,
        tag: "",
        desc: "SUV điện phổ thông, quãng đường dài hơn",
        descLong: "Phiên bản cao cấp của Atto 2 với dung lượng pin lớn hơn 45kWh, cho quãng đường lên đến 401km theo chuẩn CLTC. Phù hợp cho những người cần quãng đường di chuyển xa hơn mà vẫn muốn sở hữu một chiếc xe điện giá hợp lý.",
        img: "https://aka.doubaocdn.com/s/FyzbEEuhpc",
        gallery: [
            "https://aka.doubaocdn.com/s/FyzbEEuhpc",
            "https://aka.doubaocdn.com/s/qSUsLsT2c8",
            "https://aka.doubaocdn.com/s/vumoQMpfhT"
        ],
        specs: {
            "Kích thước": "4310×1830×1675mm",
            "Chiều dài cơ sở": "2620mm",
            "Quãng đường CLTC": "401km",
            "Công suất động cơ": "70kW (95 mã lực)",
            "Mô-men xoắn": "180Nm",
            "Dung lượng pin": "45kWh",
            "Loại pin": "Blade Battery (LFP)",
            "Sạc nhanh DC": "30%-80% trong 30 phút",
            "Sạc chậm AC": "6.6kW",
            "Tốc độ tối đa": "150km/h",
            "0-100km/h": "~10 giây",
            "Số chỗ ngồi": "5 chỗ"
        },
        features: [
            "Màn hình trung tâm 12.8 inch",
            "Đèn LED toàn xe",
            "Camera 360 độ",
            "Cảnh báo điểm mù",
            "Giữ làn đường",
            "Phanh khẩn cấp tự động",
            "Điều hòa tự động",
            "Lốp 16 inch",
            "Khe cắm sạc Type 2",
            "Khởi động không chìa khóa"
        ],
        competitor: { name: "VinFast VF 5 Plus", price: 15.1, range: "350km" }
    },
    {
        id: 3,
        name: "BYD Atto 3 510KM",
        nameCn: "第二代元PLUS智驾版 510KM领先型",
        nameVn: "BYD Atto 3 510KM",
        type: "BEV",
        body: "suv",
        range: "510km",
        power: "150kW",
        battery: "Blade Battery 60.5kWh",
        fob: 14.92,
        market: 21.82,
        tag: "best",
        desc: "SUV điện bán chạy nhất, đã có mặt tại Việt Nam",
        descLong: "BYD Atto 3 (元PLUS) là mẫu SUV điện cỡ紧凑 bán chạy nhất của BYD tại thị trường quốc tế. Với quãng đường 510km, công suất 150kW và thiết kế hiện đại, đây là lựa chọn hoàn hảo cho gia đình. Xe đã được phân phối chính hãng tại Việt Nam, có sẵn mạng lưới bảo hành.",
        img: "https://aka.doubaocdn.com/s/NDPBLf7AHr",
        gallery: [
            "https://aka.doubaocdn.com/s/NDPBLf7AHr",
            "https://aka.doubaocdn.com/s/EByphK17Yd",
            "https://aka.doubaocdn.com/s/QlE7SL8z6J"
        ],
        specs: {
            "Kích thước": "4455×1875×1615mm",
            "Chiều dài cơ sở": "2720mm",
            "Quãng đường CLTC": "510km",
            "Công suất động cơ": "150kW (201 mã lực)",
            "Mô-men xoắn": "310Nm",
            "Dung lượng pin": "60.5kWh",
            "Loại pin": "Blade Battery (LFP)",
            "Sạc nhanh DC": "30%-80% trong 30 phút",
            "Sạc chậm AC": "7kW",
            "Tốc độ tối đa": "160km/h",
            "0-100km/h": "7.3 giây",
            "Số chỗ ngồi": "5 chỗ"
        },
        features: [
            "Màn hình trung tâm 12.8 inch xoay được",
            "Đèn LED matrix",
            "Camera 360 độ",
            "Cảnh báo điểm mù",
            "Giữ làn đường chủ động",
            "Phanh khẩn cấp tự động",
            "Điều hòa tự động 2 vùng",
            "Lốp 18 inch",
            "Khe cắm sạc Type 2",
            "Ghế da tổng hợp",
            "Cửa sổ trời",
            "Âm thanh 8 loa"
        ],
        competitor: { name: "VinFast VF 7", price: 22.5, range: "450km" }
    },
    {
        id: 4,
        name: "BYD Qin Plus DM-i 128KM",
        nameCn: "2026款秦PLUS DM-i 128KM进取型",
        nameVn: "BYD Qin Plus DM-i 128KM",
        type: "DM-i",
        body: "sedan",
        range: "128km (điện)",
        power: "1.5L",
        battery: "DM-i 5.0 18kWh",
        fob: 9.59,
        market: 18.26,
        tag: "",
        desc: "Sedan lai sạc, tổng hợp 1200km+, tiết kiệm nhiên liệu",
        descLong: "BYD Qin Plus DM-i là mẫu sedan lai cắm điện bán chạy nhất Trung Quốc. Với công nghệ DM-i 5.0 thế hệ mới, xe có quãng đường chạy điện 128km và tổng hợp lên đến 1200km. Mức tiêu thụ nhiên liệu chỉ 2.9L/100km, cực kỳ tiết kiệm. Đây là mẫu xe độc quyền, không bán chính hãng tại Việt Nam.",
        img: "https://aka.doubaocdn.com/s/t8QCMagyBN",
        gallery: [
            "https://aka.doubaocdn.com/s/t8QCMagyBN",
            "https://aka.doubaocdn.com/s/ZEjauh0UzP",
            "https://aka.doubaocdn.com/s/xjx7CzDhYJ"
        ],
        specs: {
            "Kích thước": "4765×1837×1495mm",
            "Chiều dài cơ sở": "2718mm",
            "Quãng đường điện": "128km (CLTC)",
            "Quãng đường tổng hợp": "1200km+",
            "Động cơ xăng": "1.5L 101 mã lực",
            "Động cơ điện": "120kW (163 mã lực)",
            "Dung lượng pin": "18kWh",
            "Loại pin": "Blade Battery (LFP)",
            "Mức tiêu thụ": "2.9L/100km",
            "Sạc nhanh DC": "30%-80% trong 30 phút",
            "Hộp số": "E-CVT",
            "Số chỗ ngồi": "5 chỗ"
        },
        features: [
            "Màn hình trung tâm 10.1 inch",
            "Đèn LED toàn xe",
            "Camera lùi",
            "Cảm biến khoảng cách",
            "Điều hòa tự động",
            "Khởi động không chìa khóa",
            "Ghế vải cao cấp",
            "Lốp 16 inch",
            "Hỗ trợ đi lên dốc",
            "Phanh điện tử giữ xe"
        ],
        competitor: { name: "Toyota Corolla Cross Hybrid", price: 22.0, range: "Hybrid" }
    },
    {
        id: 5,
        name: "BYD Qin Plus DM-i 210KM",
        nameCn: "2026款秦PLUS DM-i 210KM进取型",
        nameVn: "BYD Qin Plus DM-i 210KM",
        type: "DM-i",
        body: "sedan",
        range: "210km (điện)",
        power: "1.5L",
        battery: "DM-i 5.0 26kWh",
        fob: 10.89,
        market: 20.63,
        tag: "",
        desc: "Sedan lai sạc, quãng đường điện 210km",
        descLong: "Phiên bản cao cấp của Qin Plus DM-i với dung lượng pin lớn hơn 26kWh, cho quãng đường chạy điện lên đến 210km. Với quãng đường này, hầu hết các chuyến đi hàng ngày có thể hoàn toàn bằng điện, không cần dùng xăng. Tổng hợp quãng đường lên đến 1400km.",
        img: "https://aka.doubaocdn.com/s/t8QCMagyBN",
        gallery: [
            "https://aka.doubaocdn.com/s/t8QCMagyBN",
            "https://aka.doubaocdn.com/s/ZEjauh0UzP",
            "https://aka.doubaocdn.com/s/xjx7CzDhYJ"
        ],
        specs: {
            "Kích thước": "4765×1837×1495mm",
            "Chiều dài cơ sở": "2718mm",
            "Quãng đường điện": "210km (CLTC)",
            "Quãng đường tổng hợp": "1400km+",
            "Động cơ xăng": "1.5L 101 mã lực",
            "Động cơ điện": "120kW (163 mã lực)",
            "Dung lượng pin": "26kWh",
            "Loại pin": "Blade Battery (LFP)",
            "Mức tiêu thụ": "2.9L/100km",
            "Sạc nhanh DC": "30%-80% trong 30 phút",
            "Hộp số": "E-CVT",
            "Số chỗ ngồi": "5 chỗ"
        },
        features: [
            "Màn hình trung tâm 12.8 inch",
            "Đèn LED toàn xe",
            "Camera 360 độ",
            "Cảm biến khoảng cách",
            "Điều hòa tự động",
            "Khởi động không chìa khóa",
            "Ghế da tổng hợp",
            "Lốp 17 inch",
            "Cửa sổ trời",
            "Phanh điện tử giữ xe"
        ],
        competitor: { name: "Toyota Corolla Altis Hybrid", price: 23.3, range: "Hybrid" }
    },
    {
        id: 6,
        name: "BYD Qin Plus EV 510KM",
        nameCn: "第二代秦PLUS EV智驾版510KM进取型",
        nameVn: "BYD Qin Plus EV 510KM",
        type: "BEV",
        body: "sedan",
        range: "510km",
        power: "100kW",
        battery: "Blade Battery 57kWh",
        fob: 12.64,
        market: 18.59,
        tag: "new",
        desc: "Sedan điện, quãng đường 510km",
        descLong: "BYD Qin Plus EV là phiên bản thuần điện của dòng Qin Plus. Với thiết kế sedan thể thao, quãng đường 510km và giá hợp lý, đây là lựa chọn tuyệt vời cho những người thích kiểu dáng sedan. Xe thế hệ thứ hai được nâng cấp về công nghệ và thiết kế.",
        img: "https://aka.doubaocdn.com/s/3IIOjUmFgP",
        gallery: [
            "https://aka.doubaocdn.com/s/3IIOjUmFgP",
            "https://aka.doubaocdn.com/s/NGcfOmsnN0",
            "https://aka.doubaocdn.com/s/PLtCQiGUR3"
        ],
        specs: {
            "Kích thước": "4765×1837×1515mm",
            "Chiều dài cơ sở": "2718mm",
            "Quãng đường CLTC": "510km",
            "Công suất động cơ": "100kW (136 mã lực)",
            "Mô-men xoắn": "180Nm",
            "Dung lượng pin": "57kWh",
            "Loại pin": "Blade Battery (LFP)",
            "Sạc nhanh DC": "30%-80% trong 30 phút",
            "Sạc chậm AC": "7kW",
            "Tốc độ tối đa": "150km/h",
            "0-100km/h": "~9 giây",
            "Số chỗ ngồi": "5 chỗ"
        },
        features: [
            "Màn hình trung tâm 12.8 inch",
            "Đèn LED toàn xe",
            "Camera 360 độ",
            "Cảnh báo điểm mù",
            "Giữ làn đường",
            "Phanh khẩn cấp tự động",
            "Điều hòa tự động",
            "Lốp 17 inch",
            "Ghế da tổng hợp",
            "Khởi động không chìa khóa"
        ],
        competitor: { name: "VinFast VF 6", price: 19.7, range: "400km" }
    },
    {
        id: 7,
        name: "BYD Qin L DM-i 128KM",
        nameCn: "2026款秦L DM-i 128KM进取型",
        nameVn: "BYD Qin L DM-i 128KM",
        type: "DM-i",
        body: "sedan",
        range: "128km (điện)",
        power: "1.5L",
        battery: "DM-i 5.0 18kWh",
        fob: 11.13,
        market: 21.07,
        tag: "",
        desc: "Sedan lai sạc cao cấp, thiết kế mới",
        descLong: "BYD Qin L là mẫu sedan cỡ trung thế hệ mới, với thiết kế thể thao và công nghệ DM-i 5.0. Xe có kích thước lớn hơn Qin Plus, mang lại không gian nội thất rộng rãi hơn. Đây là mẫu xe độc quyền, không bán chính hãng tại Việt Nam.",
        img: "https://aka.doubaocdn.com/s/oxbV8tcRel",
        gallery: [
            "https://aka.doubaocdn.com/s/oxbV8tcRel",
            "https://aka.doubaocdn.com/s/UOu7VG4ymi",
            "https://aka.doubaocdn.com/s/IQY56REAmm"
        ],
        specs: {
            "Kích thước": "4830×1900×1495mm",
            "Chiều dài cơ sở": "2790mm",
            "Quãng đường điện": "128km (CLTC)",
            "Quãng đường tổng hợp": "1200km+",
            "Động cơ xăng": "1.5L 101 mã lực",
            "Động cơ điện": "120kW (163 mã lực)",
            "Dung lượng pin": "18kWh",
            "Loại pin": "Blade Battery (LFP)",
            "Mức tiêu thụ": "2.9L/100km",
            "Sạc nhanh DC": "30%-80% trong 30 phút",
            "Hộp số": "E-CVT",
            "Số chỗ ngồi": "5 chỗ"
        },
        features: [
            "Màn hình trung tâm 12.8 inch xoay được",
            "Đèn LED matrix",
            "Camera 360 độ",
            "Cảnh báo điểm mù",
            "Giữ làn đường chủ động",
            "Phanh khẩn cấp tự động",
            "Điều hòa tự động 2 vùng",
            "Lốp 17 inch",
            "Ghế da tổng hợp",
            "Khởi động không chìa khóa",
            "Cửa sổ trời"
        ],
        competitor: { name: "Toyota Camry Hybrid", price: 30.0, range: "Hybrid" }
    },
    {
        id: 8,
        name: "BYD Qin L DM-i 128KM Premium",
        nameCn: "2026款秦L DM-i 128KM领先型",
        nameVn: "BYD Qin L DM-i 128KM Premium",
        type: "DM-i",
        body: "sedan",
        range: "128km (điện)",
        power: "1.5L",
        battery: "DM-i 5.0 18kWh",
        fob: 12.36,
        market: 23.31,
        tag: "",
        desc: "Sedan lai sạc cao cấp, đầy đủ trang bị",
        descLong: "Phiên bản cao cấp của Qin L DM-i với đầy đủ trang bị an toàn và tiện nghi. Bao gồm hệ thống hỗ trợ lái xe tiên tiến DiPilot, ghế điện, âm thanh cao cấp và nhiều công nghệ khác. Lựa chọn hoàn hảo cho những người muốn một chiếc sedan sang trọng mà giá hợp lý.",
        img: "https://aka.doubaocdn.com/s/oxbV8tcRel",
        gallery: [
            "https://aka.doubaocdn.com/s/oxbV8tcRel",
            "https://aka.doubaocdn.com/s/UOu7VG4ymi",
            "https://aka.doubaocdn.com/s/IQY56REAmm"
        ],
        specs: {
            "Kích thước": "4830×1900×1495mm",
            "Chiều dài cơ sở": "2790mm",
            "Quãng đường điện": "128km (CLTC)",
            "Quãng đường tổng hợp": "1200km+",
            "Động cơ xăng": "1.5L 101 mã lực",
            "Động cơ điện": "120kW (163 mã lực)",
            "Dung lượng pin": "18kWh",
            "Loại pin": "Blade Battery (LFP)",
            "Mức tiêu thụ": "2.9L/100km",
            "Sạc nhanh DC": "30%-80% trong 30 phút",
            "Hộp số": "E-CVT",
            "Số chỗ ngồi": "5 chỗ"
        },
        features: [
            "Màn hình trung tâm 15.6 inch xoay được",
            "Đèn LED matrix",
            "Camera 360 độ 3D",
            "Cảnh báo điểm mù",
            "Giữ làn đường chủ động",
            "Phanh khẩn cấp tự động",
            "Điều hòa tự động 2 vùng",
            "Lốp 18 inch",
            "Ghế da thật điện",
            "Ghế lái có nhớ vị trí",
            "Âm thanh 8 loa cao cấp",
            "Cửa sổ trời panorama"
        ],
        competitor: { name: "Honda Accord Hybrid", price: 33.4, range: "Hybrid" }
    },
    {
        id: 9,
        name: "BYD Qin L DM-i 210KM",
        nameCn: "2026款秦L DM-i 210KM超越型",
        nameVn: "BYD Qin L DM-i 210KM",
        type: "DM-i",
        body: "sedan",
        range: "210km (điện)",
        power: "1.5L",
        battery: "DM-i 5.0 26kWh",
        fob: 14.38,
        market: 26.99,
        tag: "",
        desc: "Sedan lai sạc cao cấp nhất, quãng đường 210km",
        descLong: "Phiên bản cao cấp nhất của dòng Qin L với dung lượng pin 26kWh, cho quãng đường chạy điện 210km. Với đầy đủ trang bị cao cấp và công nghệ tiên tiến, đây là mẫu sedan lai cắm điện đáng mua nhất trong tầm giá.",
        img: "https://aka.doubaocdn.com/s/oxbV8tcRel",
        gallery: [
            "https://aka.doubaocdn.com/s/oxbV8tcRel",
            "https://aka.doubaocdn.com/s/UOu7VG4ymi",
            "https://aka.doubaocdn.com/s/IQY56REAmm"
        ],
        specs: {
            "Kích thước": "4830×1900×1495mm",
            "Chiều dài cơ sở": "2790mm",
            "Quãng đường điện": "210km (CLTC)",
            "Quãng đường tổng hợp": "1400km+",
            "Động cơ xăng": "1.5L 101 mã lực",
            "Động cơ điện": "120kW (163 mã lực)",
            "Dung lượng pin": "26kWh",
            "Loại pin": "Blade Battery (LFP)",
            "Mức tiêu thụ": "2.9L/100km",
            "Sạc nhanh DC": "30%-80% trong 30 phút",
            "Hộp số": "E-CVT",
            "Số chỗ ngồi": "5 chỗ"
        },
        features: [
            "Màn hình trung tâm 15.6 inch xoay được",
            "Đèn LED matrix",
            "Camera 360 độ 3D",
            "Hệ thống DiPilot 100",
            "Giữ làn đường chủ động",
            "Phanh khẩn cấp tự động",
            "Điều hòa tự động 2 vùng",
            "Lốp 18 inch",
            "Ghế da thật điện",
            "Ghế lái có nhớ vị trí",
            "Âm thanh 8 loa cao cấp",
            "Cửa sổ trời panorama"
        ],
        competitor: { name: "Honda CR-V e:HEV", price: 33.4, range: "Hybrid" }
    },
    {
        id: 10,
        name: "BYD Qin L EV 545KM",
        nameCn: "秦L EV 545KM超越型",
        nameVn: "BYD Qin L EV 545KM",
        type: "BEV",
        body: "sedan",
        range: "545km",
        power: "150kW",
        battery: "Blade Battery 72kWh",
        fob: 15.63,
        market: 22.83,
        tag: "new",
        desc: "Sedan điện cao cấp, cạnh tranh Tesla Model 3",
        descLong: "BYD Qin L EV là phiên bản thuần điện của dòng Qin L, với thiết kế sedan thể thao và quãng đường 545km. Với công suất 150kW và công nghệ sạc nhanh, đây là đối thủ trực tiếp của Tesla Model 3 nhưng với giá mềm hơn nhiều.",
        img: "https://aka.doubaocdn.com/s/ATwusZDkyg",
        gallery: [
            "https://aka.doubaocdn.com/s/ATwusZDkyg",
            "https://aka.doubaocdn.com/s/QGAuBTJ0it",
            "https://aka.doubaocdn.com/s/rrfYKcBkOL"
        ],
        specs: {
            "Kích thước": "4830×1900×1495mm",
            "Chiều dài cơ sở": "2790mm",
            "Quãng đường CLTC": "545km",
            "Công suất động cơ": "150kW (201 mã lực)",
            "Mô-men xoắn": "310Nm",
            "Dung lượng pin": "72kWh",
            "Loại pin": "Blade Battery (LFP)",
            "Sạc nhanh DC": "30%-80% trong 25 phút",
            "Sạc chậm AC": "7kW",
            "Tốc độ tối đa": "170km/h",
            "0-100km/h": "7.3 giây",
            "Số chỗ ngồi": "5 chỗ"
        },
        features: [
            "Màn hình trung tâm 15.6 inch xoay được",
            "Đèn LED matrix",
            "Camera 360 độ 3D",
            "Hệ thống DiPilot 100",
            "Giữ làn đường chủ động",
            "Phanh khẩn cấp tự động",
            "Điều hòa tự động 2 vùng",
            "Lốp 18 inch",
            "Ghế da thật điện",
            "Âm thanh 8 loa cao cấp",
            "Cửa sổ trời panorama",
            "Sạc nhanh 150kW"
        ],
        competitor: { name: "Tesla Model 3", price: 35.0, range: "556km" }
    },
    {
        id: 11,
        name: "BYD Song Pro DM-i 133KM",
        nameCn: "2026款宋ProDM-i 133KM进取型",
        nameVn: "BYD Song Pro DM-i 133KM",
        type: "DM-i",
        body: "suv",
        range: "133km (điện)",
        power: "1.5L",
        battery: "DM-i 5.0 18kWh",
        fob: 11.66,
        market: 22.03,
        tag: "",
        desc: "SUV lai sạc, gia đình phổ thông",
        descLong: "BYD Song Pro DM-i là mẫu SUV lai cắm điện bán chạy nhất Trung Quốc. Với không gian rộng rãi, công nghệ DM-i 5.0 và giá hợp lý, đây là lựa chọn hoàn hảo cho gia đình. Xe không bán chính hãng tại Việt Nam, cơ hội độc quyền.",
        img: "https://aka.doubaocdn.com/s/8UaaGEFWI5",
        gallery: [
            "https://aka.doubaocdn.com/s/8UaaGEFWI5",
            "https://aka.doubaocdn.com/s/nDG4k9JTbR",
            "https://aka.doubaocdn.com/s/ZT8v2E1Rc0"
        ],
        specs: {
            "Kích thước": "4738×1860×1710mm",
            "Chiều dài cơ sở": "2712mm",
            "Quãng đường điện": "133km (CLTC)",
            "Quãng đường tổng hợp": "1200km+",
            "Động cơ xăng": "1.5L 101 mã lực",
            "Động cơ điện": "120kW (163 mã lực)",
            "Dung lượng pin": "18kWh",
            "Loại pin": "Blade Battery (LFP)",
            "Mức tiêu thụ": "3.8L/100km",
            "Sạc nhanh DC": "30%-80% trong 30 phút",
            "Hộp số": "E-CVT",
            "Số chỗ ngồi": "5 chỗ"
        },
        features: [
            "Màn hình trung tâm 12.8 inch xoay được",
            "Đèn LED toàn xe",
            "Camera 360 độ",
            "Cảnh báo điểm mù",
            "Điều hòa tự động",
            "Khởi động không chìa khóa",
            "Ghế vải cao cấp",
            "Lốp 18 inch",
            "Hỗ trợ đi lên dốc",
            "Phanh điện tử giữ xe"
        ],
        competitor: { name: "Toyota Corolla Cross Hybrid", price: 22.0, range: "Hybrid" }
    },
    {
        id: 12,
        name: "BYD Song Pro DM-i 133KM Premium",
        nameCn: "2026款宋ProDM-i 133KM超越型",
        nameVn: "BYD Song Pro DM-i 133KM Premium",
        type: "DM-i",
        body: "suv",
        range: "133km (điện)",
        power: "1.5L",
        battery: "DM-i 5.0 18kWh",
        fob: 12.90,
        market: 24.29,
        tag: "",
        desc: "SUV lai sạc, đầy đủ trang bị",
        descLong: "Phiên bản cao cấp của Song Pro DM-i với đầy đủ trang bị an toàn và tiện nghi. Bao gồm hệ thống hỗ trợ lái xe DiPilot, ghế điện, âm thanh cao cấp và nhiều công nghệ khác. Lựa chọn hoàn hảo cho gia đình muốn một chiếc SUV đầy đủ tính năng.",
        img: "https://aka.doubaocdn.com/s/8UaaGEFWI5",
        gallery: [
            "https://aka.doubaocdn.com/s/8UaaGEFWI5",
            "https://aka.doubaocdn.com/s/nDG4k9JTbR",
            "https://aka.doubaocdn.com/s/ZT8v2E1Rc0"
        ],
        specs: {
            "Kích thước": "4738×1860×1710mm",
            "Chiều dài cơ sở": "2712mm",
            "Quãng đường điện": "133km (CLTC)",
            "Quãng đường tổng hợp": "1200km+",
            "Động cơ xăng": "1.5L 101 mã lực",
            "Động cơ điện": "120kW (163 mã lực)",
            "Dung lượng pin": "18kWh",
            "Loại pin": "Blade Battery (LFP)",
            "Mức tiêu thụ": "3.8L/100km",
            "Sạc nhanh DC": "30%-80% trong 30 phút",
            "Hộp số": "E-CVT",
            "Số chỗ ngồi": "5 chỗ"
        },
        features: [
            "Màn hình trung tâm 15.6 inch xoay được",
            "Đèn LED matrix",
            "Camera 360 độ 3D",
            "Hệ thống DiPilot 100",
            "Giữ làn đường chủ động",
            "Phanh khẩn cấp tự động",
            "Điều hòa tự động 2 vùng",
            "Lốp 19 inch",
            "Ghế da thật điện",
            "Âm thanh 8 loa cao cấp",
            "Cửa sổ trời panorama",
            "Ghế lái có nhớ vị trí"
        ],
        competitor: { name: "Honda CR-V e:HEV", price: 33.4, range: "Hybrid" }
    },
    {
        id: 13,
        name: "BYD Song Pro DM-i 220KM",
        nameCn: "2026款宋ProDM-i 220KM超越型",
        nameVn: "BYD Song Pro DM-i 220KM",
        type: "DM-i",
        body: "suv",
        range: "220km (điện)",
        power: "1.5L",
        battery: "DM-i 5.0 27kWh",
        fob: 14.67,
        market: 27.51,
        tag: "",
        desc: "SUV lai sạc cao cấp nhất, quãng đường 220km",
        descLong: "Phiên bản cao cấp nhất của dòng Song Pro với dung lượng pin 27kWh, cho quãng đường chạy điện 220km. Với đầy đủ trang bị cao cấp và công nghệ tiên tiến, đây là mẫu SUV lai cắm điện đáng mua nhất trong tầm giá.",
        img: "https://aka.doubaocdn.com/s/8UaaGEFWI5",
        gallery: [
            "https://aka.doubaocdn.com/s/8UaaGEFWI5",
            "https://aka.doubaocdn.com/s/nDG4k9JTbR",
            "https://aka.doubaocdn.com/s/ZT8v2E1Rc0"
        ],
        specs: {
            "Kích thước": "4738×1860×1710mm",
            "Chiều dài cơ sở": "2712mm",
            "Quãng đường điện": "220km (CLTC)",
            "Quãng đường tổng hợp": "1400km+",
            "Động cơ xăng": "1.5L 101 mã lực",
            "Động cơ điện": "120kW (163 mã lực)",
            "Dung lượng pin": "27kWh",
            "Loại pin": "Blade Battery (LFP)",
            "Mức tiêu thụ": "3.8L/100km",
            "Sạc nhanh DC": "30%-80% trong 30 phút",
            "Hộp số": "E-CVT",
            "Số chỗ ngồi": "5 chỗ"
        },
        features: [
            "Màn hình trung tâm 15.6 inch xoay được",
            "Đèn LED matrix",
            "Camera 360 độ 3D",
            "Hệ thống DiPilot 100",
            "Giữ làn đường chủ động",
            "Phanh khẩn cấp tự động",
            "Điều hòa tự động 2 vùng",
            "Lốp 19 inch",
            "Ghế da thật điện",
            "Âm thanh 8 loa cao cấp",
            "Cửa sổ trời panorama",
            "Sạc nhanh 100kW"
        ],
        competitor: { name: "Honda CR-V e:HEV", price: 33.4, range: "Hybrid" }
    },
    {
        id: 14,
        name: "BYD Song Pro DM-i Racing 220KM",
        nameCn: "宋ProDM-i飞驰版 220KM领先型",
        nameVn: "BYD Song Pro DM-i Racing 220KM",
        type: "DM-i",
        body: "suv",
        range: "220km (điện)",
        power: "1.5L",
        battery: "DM-i 5.0 27kWh",
        fob: 12.82,
        market: 24.14,
        tag: "",
        desc: "SUV lai sạc thể thao, bản Racing",
        descLong: "Phiên bản Racing (飞驰版) của Song Pro DM-i với thiết kế thể thao hơn, bao gồm body kit, đèn sau dạng xuyên thấu và nội thất mang đậm chất thể thao. Vẫn giữ nguyên công nghệ DM-i 5.0 và quãng đường 220km.",
        img: "https://aka.doubaocdn.com/s/8UaaGEFWI5",
        gallery: [
            "https://aka.doubaocdn.com/s/8UaaGEFWI5",
            "https://aka.doubaocdn.com/s/nDG4k9JTbR",
            "https://aka.doubaocdn.com/s/ZT8v2E1Rc0"
        ],
        specs: {
            "Kích thước": "4738×1860×1710mm",
            "Chiều dài cơ sở": "2712mm",
            "Quãng đường điện": "220km (CLTC)",
            "Quãng đường tổng hợp": "1400km+",
            "Động cơ xăng": "1.5L 101 mã lực",
            "Động cơ điện": "120kW (163 mã lực)",
            "Dung lượng pin": "27kWh",
            "Loại pin": "Blade Battery (LFP)",
            "Mức tiêu thụ": "3.8L/100km",
            "Sạc nhanh DC": "30%-80% trong 30 phút",
            "Hộp số": "E-CVT",
            "Số chỗ ngồi": "5 chỗ"
        },
        features: [
            "Màn hình trung tâm 12.8 inch xoay được",
            "Đèn LED matrix",
            "Body kit thể thao",
            "Đèn sau xuyên thấu",
            "Camera 360 độ",
            "Điều hòa tự động",
            "Ghế vải thể thao",
            "Lốp 19 inch thể thao",
            "Khởi động không chìa khóa",
            "Phanh điện tử giữ xe"
        ],
        competitor: { name: "Toyota Corolla Cross Hybrid", price: 22.0, range: "Hybrid" }
    },
    {
        id: 15,
        name: "BYD Song Pro DM-i Racing 220KM Premium",
        nameCn: "宋ProDM-i飞驰版 220KM超越型",
        nameVn: "BYD Song Pro DM-i Racing 220KM Premium",
        type: "DM-i",
        body: "suv",
        range: "220km (điện)",
        power: "1.5L",
        battery: "DM-i 5.0 27kWh",
        fob: 15.05,
        market: 28.21,
        tag: "",
        desc: "SUV lai sạc thể thao, bản cao cấp",
        descLong: "Phiên bản cao cấp của dòng Racing với đầy đủ trang bị. Thiết kế thể thao kết hợp cùng công nghệ tiên tiến, mang lại trải nghiệm lái xe thú vị. Lựa chọn cho những người thích phong cách thể thao mà vẫn cần sự tiện nghi của SUV.",
        img: "https://aka.doubaocdn.com/s/8UaaGEFWI5",
        gallery: [
            "https://aka.doubaocdn.com/s/8UaaGEFWI5",
            "https://aka.doubaocdn.com/s/nDG4k9JTbR",
            "https://aka.doubaocdn.com/s/ZT8v2E1Rc0"
        ],
        specs: {
            "Kích thước": "4738×1860×1710mm",
            "Chiều dài cơ sở": "2712mm",
            "Quãng đường điện": "220km (CLTC)",
            "Quãng đường tổng hợp": "1400km+",
            "Động cơ xăng": "1.5L 101 mã lực",
            "Động cơ điện": "120kW (163 mã lực)",
            "Dung lượng pin": "27kWh",
            "Loại pin": "Blade Battery (LFP)",
            "Mức tiêu thụ": "3.8L/100km",
            "Sạc nhanh DC": "30%-80% trong 30 phút",
            "Hộp số": "E-CVT",
            "Số chỗ ngồi": "5 chỗ"
        },
        features: [
            "Màn hình trung tâm 15.6 inch xoay được",
            "Đèn LED matrix",
            "Body kit thể thao",
            "Đèn sau xuyên thấu",
            "Camera 360 độ 3D",
            "Hệ thống DiPilot 100",
            "Điều hòa tự động 2 vùng",
            "Lốp 19 inch thể thao",
            "Ghế da thật điện thể thao",
            "Âm thanh 8 loa cao cấp",
            "Cửa sổ trời panorama"
        ],
        competitor: { name: "Honda CR-V e:HEV", price: 33.4, range: "Hybrid" }
    },
    {
        id: 16,
        name: "BYD Song Pro DM-i Racing 301KM",
        nameCn: "宋ProDM-i飞驰版 301KM超越型",
        nameVn: "BYD Song Pro DM-i Racing 301KM",
        type: "DM-i",
        body: "suv",
        range: "301km (điện)",
        power: "1.5L",
        battery: "DM-i 5.0 36kWh",
        fob: 15.43,
        market: 28.90,
        tag: "",
        desc: "SUV lai sạc thể thao, quãng đường dài nhất 301km",
        descLong: "Phiên bản có quãng đường chạy điện dài nhất trong dòng Song Pro, lên đến 301km. Với dung lượng pin 36kWh, hầu hết các chuyến đi hàng ngày có thể hoàn toàn bằng điện. Kết hợp thiết kế thể thao của dòng Racing.",
        img: "https://aka.doubaocdn.com/s/8UaaGEFWI5",
        gallery: [
            "https://aka.doubaocdn.com/s/8UaaGEFWI5",
            "https://aka.doubaocdn.com/s/nDG4k9JTbR",
            "https://aka.doubaocdn.com/s/ZT8v2E1Rc0"
        ],
        specs: {
            "Kích thước": "4738×1860×1710mm",
            "Chiều dài cơ sở": "2712mm",
            "Quãng đường điện": "301km (CLTC)",
            "Quãng đường tổng hợp": "1500km+",
            "Động cơ xăng": "1.5L 101 mã lực",
            "Động cơ điện": "120kW (163 mã lực)",
            "Dung lượng pin": "36kWh",
            "Loại pin": "Blade Battery (LFP)",
            "Mức tiêu thụ": "3.8L/100km",
            "Sạc nhanh DC": "30%-80% trong 30 phút",
            "Hộp số": "E-CVT",
            "Số chỗ ngồi": "5 chỗ"
        },
        features: [
            "Màn hình trung tâm 15.6 inch xoay được",
            "Đèn LED matrix",
            "Body kit thể thao",
            "Đèn sau xuyên thấu",
            "Camera 360 độ 3D",
            "Hệ thống DiPilot 100",
            "Điều hòa tự động 2 vùng",
            "Lốp 19 inch thể thao",
            "Ghế da thật điện thể thao",
            "Âm thanh 8 loa cao cấp",
            "Cửa sổ trời panorama",
            "Sạc nhanh 100kW"
        ],
        competitor: { name: "Honda CR-V e:HEV", price: 33.4, range: "Hybrid" }
    },
    {
        id: 17,
        name: "BYD Song L DM-i 200KM",
        nameCn: "2026款宋L DM-i 200KM超越型",
        nameVn: "BYD Song L DM-i 200KM",
        type: "DM-i",
        body: "suv",
        range: "200km (điện)",
        power: "1.5L",
        battery: "DM-i 5.0 26kWh",
        fob: 18.59,
        market: 34.65,
        tag: "flagship",
        desc: "SUV lai sạc hàng đầu, định vị cao cấp",
        descLong: "BYD Song L DM-i là mẫu SUV cỡ trung cao cấp, với thiết kế coupe thể thao và công nghệ tiên tiến. Xe có kích thước lớn, không gian nội thất rộng rãi và đầy đủ trang bị cao cấp. Đây là mẫu xe hàng đầu trong dòng sản phẩm của chúng tôi.",
        img: "https://aka.doubaocdn.com/s/HG3SbspKWD",
        gallery: [
            "https://aka.doubaocdn.com/s/HG3SbspKWD",
            "https://aka.doubaocdn.com/s/VW8VvDhdFv",
            "https://aka.doubaocdn.com/s/MpmrTUIZR7"
        ],
        specs: {
            "Kích thước": "4840×1950×1560mm",
            "Chiều dài cơ sở": "2930mm",
            "Quãng đường điện": "200km (CLTC)",
            "Quãng đường tổng hợp": "1300km+",
            "Động cơ xăng": "1.5L 101 mã lực",
            "Động cơ điện": "160kW (218 mã lực)",
            "Dung lượng pin": "26kWh",
            "Loại pin": "Blade Battery (LFP)",
            "Mức tiêu thụ": "4.5L/100km",
            "Sạc nhanh DC": "30%-80% trong 25 phút",
            "Hộp số": "E-CVT",
            "Số chỗ ngồi": "5 chỗ"
        },
        features: [
            "Màn hình trung tâm 15.6 inch xoay được",
            "Đèn LED matrix",
            "Camera 360 độ 3D",
            "Hệ thống DiPilot 100",
            "Giữ làn đường chủ động",
            "Phanh khẩn cấp tự động",
            "Điều hòa tự động 2 vùng",
            "Lốp 20 inch",
            "Ghế da thật điện",
            "Ghế lái có nhớ vị trí",
            "Âm thanh 12 loa cao cấp",
            "Cửa sổ trời panorama"
        ],
        competitor: { name: "Honda CR-V e:HEV", price: 33.4, range: "Hybrid" }
    },
    {
        id: 18,
        name: "BYD Song Ultra EV 605KM",
        nameCn: "宋Ultra EV 605KM 领先型",
        nameVn: "BYD Song Ultra EV 605KM",
        type: "BEV",
        body: "suv",
        range: "605km",
        power: "230kW",
        battery: "Blade Battery 87kWh",
        fob: 20.09,
        market: 29.15,
        tag: "flagship",
        desc: "SUV điện hàng đầu, 605km, AWD",
        descLong: "BYD Song Ultra EV là mẫu SUV điện cao cấp nhất, với quãng đường 605km, hệ thống dẫn động 4 bánh AWD và công nghệ sạc nhanh thế hệ mới. Xe được trang bị đầy đủ công nghệ tiên tiến nhất của BYD, mang lại trải nghiệm lái xe đẳng cấp.",
        img: "https://aka.doubaocdn.com/s/xoPzuefCgc",
        gallery: [
            "https://aka.doubaocdn.com/s/xoPzuefCgc",
            "https://aka.doubaocdn.com/s/7qra25xugE",
            "https://aka.doubaocdn.com/s/ZfVUUoVAv0"
        ],
        specs: {
            "Kích thước": "4840×1950×1560mm",
            "Chiều dài cơ sở": "2930mm",
            "Quãng đường CLTC": "605km",
            "Công suất động cơ": "230kW (313 mã lực) AWD",
            "Mô-men xoắn": "420Nm",
            "Dung lượng pin": "87kWh",
            "Loại pin": "Blade Battery thế hệ 2 (LFP)",
            "Sạc nhanh DC": "10%-80% trong 19 phút",
            "Sạc chậm AC": "11kW",
            "Tốc độ tối đa": "180km/h",
            "0-100km/h": "5.9 giây",
            "Số chỗ ngồi": "5 chỗ"
        },
        features: [
            "Màn hình trung tâm 15.6 inch xoay được",
            "Đèn LED matrix",
            "Camera 360 độ 3D",
            "Hệ thống DiPilot 100",
            "Hệ thống treo khí nén DiSus-C",
            "Giữ làn đường chủ động",
            "Phanh khẩn cấp tự động",
            "Điều hòa tự động 2 vùng",
            "Lốp 20 inch",
            "Ghế da thật điện",
            "Âm thanh 12 loa cao cấp",
            "Cửa sổ trời panorama",
            "Sạc nhanh 150kW"
        ],
        competitor: { name: "VinFast VF 8", price: 27.8, range: "550km" }
    },
    {
        id: 19,
        name: "BYD Song Ultra EV 605KM Premium",
        nameCn: "宋Ultra EV 605KM 超越型",
        nameVn: "BYD Song Ultra EV 605KM Premium",
        type: "BEV",
        body: "suv",
        range: "605km",
        power: "230kW",
        battery: "Blade Battery 87kWh",
        fob: 21.90,
        market: 31.72,
        tag: "flagship",
        desc: "SUV điện hàng đầu, bản cao cấp nhất",
        descLong: "Phiên bản cao cấp nhất của dòng Song Ultra EV với đầy đủ trang bị đỉnh cao. Bao gồm hệ thống treo khí nén DiSus-C, công nghệ sạc nhanh 150kW, hệ thống hỗ trợ lái xe tiên tiến và nhiều trang bị sang trọng khác. Đây là mẫu xe điện đẳng cấp nhất trong danh mục của chúng tôi.",
        img: "https://aka.doubaocdn.com/s/xoPzuefCgc",
        gallery: [
            "https://aka.doubaocdn.com/s/xoPzuefCgc",
            "https://aka.doubaocdn.com/s/7qra25xugE",
            "https://aka.doubaocdn.com/s/ZfVUUoVAv0"
        ],
        specs: {
            "Kích thước": "4840×1950×1560mm",
            "Chiều dài cơ sở": "2930mm",
            "Quãng đường CLTC": "605km",
            "Công suất động cơ": "230kW (313 mã lực) AWD",
            "Mô-men xoắn": "420Nm",
            "Dung lượng pin": "87kWh",
            "Loại pin": "Blade Battery thế hệ 2 (LFP)",
            "Sạc nhanh DC": "10%-80% trong 19 phút",
            "Sạc chậm AC": "11kW",
            "Tốc độ tối đa": "180km/h",
            "0-100km/h": "5.9 giây",
            "Số chỗ ngồi": "5 chỗ"
        },
        features: [
            "Màn hình trung tâm 15.6 inch xoay được",
            "Đầu xe HUD",
            "Đèn LED matrix",
            "Camera 360 độ 3D",
            "Hệ thống DiPilot 100",
            "Hệ thống treo khí nén DiSus-C",
            "Giữ làn đường chủ động",
            "Phanh khẩn cấp tự động",
            "Điều hòa tự động 2 vùng",
            "Lốp 21 inch",
            "Ghế da thật điện có massage",
            "Âm thanh 12 loa cao cấp Dynaudio",
            "Cửa sổ trời panorama",
            "Sạc nhanh 150kW"
        ],
        competitor: { name: "VinFast VF 8 Plus", price: 30.0, range: "550km" }
    }
];

// ===== Helper Functions =====
function getCarById(id) {
    return cars.find(c => c.id === parseInt(id));
}

function getRelatedCars(currentId, count = 3) {
    const current = getCarById(currentId);
    if (!current) return cars.slice(0, count);
    return cars.filter(c => c.id !== currentId && c.body === current.body).slice(0, count);
}

function calculateLandedCost(car) {
    const taxRate = car.type === 'BEV' ? 0.134 : 0.457;
    const cif = car.fob + 0.3;
    const landed = Math.round(cif * (1 + taxRate) * 100) / 100;
    const retail = Math.round(landed * 1.25 * 100) / 100;
    const profit = Math.round((retail - landed) * 100) / 100;
    return { cif, landed, retail, profit, taxRate };
}

function formatPrice(wan) {
    return '¥' + wan + '万';
}

function formatVND(wan) {
    const vnd = wan * 10000 * 3500;
    if (vnd >= 1000000000) return (vnd / 1000000000).toFixed(2) + ' tỷ VND';
    return (vnd / 1000000).toFixed(0) + ' triệu VND';
}
